import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {chromium} from '@playwright/test';
const portraitHashes={
 'assets/img/hero-raigad.jpg':'32526fb78b127e163b42ca1d346e61502e51f78d3e672144f90aea02d8d29e47',
 'public/images/hero-raigad-480.webp':'468fd929f9df6af9a99c06a016e5d45edbefc8ebf7ecd8bf2cc04cbf3db3bfd9',
 'public/images/hero-raigad-960.webp':'e9508dbebfc1face65e10e15fbdb4ac38d10e5af1725e339e14e2224d5240321',
 'public/images/hero-raigad-1600.webp':'fbc0078552dd236a61c4e93ab2664a6420448312108182848bd28545c8abce70'
};
for(const [file,hash] of Object.entries(portraitHashes))assert.equal(createHash('sha256').update(await fs.readFile(file)).digest('hex'),hash,`${file}: main portrait changed`);
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:5173';
await fs.mkdir('test-results',{recursive:true});
await page.goto(base);await page.locator('.site-footer').waitFor();
assert.equal(await page.locator('.portrait-frame img').evaluate(el=>getComputedStyle(el).transform),'none');
await page.waitForFunction(()=>document.querySelector('.hero h1').getAnimations().length>0);
await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';const el=document.querySelector('#prologue .split__image');scrollTo(0,el.offsetTop-250);});
await page.waitForFunction(()=>document.querySelector('#prologue .split__image').getAnimations().some(a=>a.playState==='running'));
await page.waitForFunction(()=>document.querySelector('.reading-chapter.is-visible'));
const progress=await page.locator('.reading-progress').evaluate(el=>Number(el.style.getPropertyValue('--read-progress')));
assert.ok(progress>0&&progress<1,'Reading progress must follow scroll');
const image=page.locator('#prologue .artwork-image');
const before=await image.evaluate(el=>getComputedStyle(el).transform);
await page.evaluate(()=>scrollBy(0,300));await page.waitForTimeout(100);
assert.notEqual(await image.evaluate(el=>getComputedStyle(el).transform),before,'Landscape movement must follow scroll');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Normal-motion overflow');
await page.emulateMedia({reducedMotion:'reduce'});
await page.waitForFunction(()=>!document.documentElement.classList.contains('motion-enabled'));
assert.equal(await image.evaluate(el=>getComputedStyle(el).transform),'none','Reduced motion must stop parallax');
assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0,'Reduced motion must stop animations');
await page.goto(`${base}/galleries.html`);const opener=page.locator('.gallery-open').first();
await opener.click();await page.locator('dialog[open] img').evaluate(el=>el.decode());
assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');
assert.ok((await page.locator('dialog img').getAttribute('src')).includes('1600'),'Lightbox should use largest variant');
await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').count(),0);
assert.equal(await opener.evaluate(el=>el===document.activeElement),true,'Lightbox must restore keyboard focus');
assert.equal(await page.evaluate(()=>document.body.style.overflow),'');
await page.setViewportSize({width:390,height:844});await opener.click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile lightbox overflow');
await page.getByRole('button',{name:'Close image'}).click();
await page.locator('.media-credits summary').click();assert.ok(await page.locator('.credits-grid a').count()>10);
const bhavani=page.locator('.gallery-tile img[src*="bhavani-alt"]');
assert.equal(await bhavani.count(),1,'Gallery must use the sourced Bhavani photograph');
assert.equal(await page.locator('.credits-grid a[href="https://commons.wikimedia.org/wiki/File:Aai_tuljabhavani.jpg"]').count(),1,'Photographer source credit must be visible');
await page.goto(`${base}/legacy.html`);
await page.locator('#ashtapradhan .ashtapradhan-image__frame').scrollIntoViewIfNeeded();
const council=await page.locator('#ashtapradhan .ashtapradhan-image__frame').evaluate(frame=>({ratio:frame.clientWidth/frame.clientHeight,fit:getComputedStyle(frame.querySelector('img')).objectFit}));
assert.ok(council.ratio>1.4&&council.ratio<1.6&&council.fit==='contain','Council painting must be fully visible in its landscape frame');
await page.setViewportSize({width:1440,height:900});
await page.goto(`${base}/timeline.html`);await page.locator('#milestone-1680').waitFor();
await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';document.getElementById('milestone-1659').scrollIntoView({block:'center',behavior:'instant'});});
await page.waitForFunction(()=>document.querySelector('.timeline-year-display')?.textContent==='1659');
assert.equal(await page.locator('#milestone-1659').getAttribute('data-selected'),'true');
const pinnedTop=await page.locator('.timeline-map').evaluate(el=>el.getBoundingClientRect().top);
await page.evaluate(()=>document.getElementById('milestone-1680').scrollIntoView({block:'center',behavior:'instant'}));
await page.waitForFunction(()=>document.querySelector('.timeline-year-display')?.textContent==='1680');
assert.ok(Math.abs(await page.locator('.timeline-map').evaluate(el=>el.getBoundingClientRect().top)-pinnedTop)<4,'Timeline image must stay pinned while scrolling milestones');
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>document.getElementById('milestone-1646').scrollIntoView({block:'center',behavior:'instant'}));
await page.waitForFunction(()=>document.querySelector('.timeline-year-display')?.textContent==='1646');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile timeline overflow');
await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(`${base}/index.html`);await page.locator('.site-footer').waitFor();
await page.waitForTimeout(1400);await page.screenshot({path:'test-results/motion-home-mobile.png'});
await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';document.getElementById('prologue').scrollIntoView();});
await page.waitForTimeout(1400);await page.screenshot({path:'test-results/motion-prologue-mobile.png'});
assert.deepEqual(errors,[]);await browser.close();
console.log('PASS: portrait checksums, animated entrances, image parallax, progress, reduced motion, gallery lightbox, focus restoration, mobile layout, and credits.');
