import React from 'react';

// Editorial additions live outside generated JSON so archive migration cannot erase them.
// References are intentionally at work level: no unverified folio or page numbers.
const sources={
 sarkar:{title:'Shivaji and His Times',author:'Jadunath Sarkar',detail:'Historical monograph; consult a cited edition for page-specific verification.',kind:'Secondary history'},
 gazetteer:{title:'Maharashtra State Gazetteers',author:'Government of Maharashtra, Gazetteers Department',detail:'Regional gazetteer series. Fort-specific entries should be checked against the relevant district volume.',url:'https://gazetteers.maharashtra.gov.in/',kind:'Institutional reference'},
 sabhasad:{title:'Sabhasad Bakhar',author:'Krishnaji Anant Sabhasad',detail:'Early Marathi chronicle; episodes require comparison with critical editions and other records.',kind:'Primary-era narrative'}
};
const fortData={
 'fort-raigad':{
  title:['Raigad as a capital','राजधानी म्हणून रायगड'],place:['Raigad district · hill fort','रायगड जिल्हा · गिरिदुर्ग'],source:['gazetteer','sarkar'],sections:[
   [['Setting and defence','भौगोलिक स्थान व संरक्षण'],'Raigad stands on a steep Sahyadri height. Approaches, gates and stored water mattered to the functioning of a defended capital.','रायगड सह्याद्रीतील उंच डोंगरावर आहे. राजधानीच्या संरक्षणासाठी चढाईचे मार्ग, दरवाजे आणि साठवलेले पाणी महत्त्वाचे होते.'],
   [['Court and coronation','दरबार व राज्याभिषेक'],'Chhatrapati Shivaji Maharaj made Raigad his capital. The coronation held here in 1674 gave the court a new public expression of sovereignty.','छत्रपती शिवाजी महाराजांनी रायगड राजधानी केला. येथे १६७४ मध्ये झालेल्या राज्याभिषेकाने सार्वभौम सत्तेला सार्वजनिक स्वरूप दिले.'],
   [['What survives','आजचे अवशेष'],'Visitors can examine the palace precinct, gateways, water features and memorial landscape. Modern labels should distinguish surviving masonry from later restoration.','आज दरवाजे, राजवाडा परिसर, जलरचना आणि स्मृतिस्थळे पाहता येतात. मूळ बांधकाम आणि नंतरची दुरुस्ती वेगळी ओळखणे आवश्यक आहे.']
  ]},
 'fort-pratapgad':{
  title:['Pratapgad and the Jawali routes','प्रतापगड आणि जावळीचे मार्ग'],place:['Satara district · hill fort','सातारा जिल्हा · गिरिदुर्ग'],source:['sarkar','gazetteer'],sections:[
   [['Mountain setting','डोंगरातील स्थान'],'The fort overlooks approaches through the forested Jawali region. Its position helped watch movement between the plateau and Konkan.','जावळीच्या वनराईतील मार्गांवर या गडाचे स्थान आहे. देश आणि कोकण यांमधील हालचालींवर लक्ष ठेवणे येथे शक्य होते.'],
   [['The 1659 encounter','१६५९ मधील संघर्ष'],'The meeting between Chhatrapati Shivaji Maharaj and Afzal Khan near Pratapgad in 1659 became a turning point in the struggle with Bijapur. Accounts differ on details of the encounter.','१६५९ मध्ये प्रतापगडाजवळ छत्रपती शिवाजी महाराज आणि अफझलखान यांची भेट हा विजापूरशी संघर्षातील महत्त्वाचा टप्पा ठरला. भेटीच्या तपशिलांबाबत वर्णने वेगवेगळी आहेत.'],
   [['Reading the landscape','परिसर समजून घेताना'],'The fort and its slopes help explain why terrain was central to the campaign. A modern image cannot establish the precise positions of seventeenth-century forces.','किल्ला आणि भोवतालचा उतार या मोहिमेत भूभागाचे महत्त्व स्पष्ट करतात. आजचे छायाचित्र सतराव्या शतकातील सैन्याची अचूक ठिकाणे सिद्ध करू शकत नाही.']
  ]},
 'fort-shivneri':{
  title:['Shivneri and the early years','शिवनेरी आणि बालपण'],place:['Near Junnar, Pune district · hill fort','जुन्नरजवळ, पुणे जिल्हा · गिरिदुर्ग'],source:['gazetteer','sarkar'],sections:[
   [['A fortified birthplace','किल्ल्यावरील जन्मस्थान'],'Shivneri near Junnar is the accepted birthplace of Chhatrapati Shivaji Maharaj. The fort belongs to a much longer regional history than this single event.','जुन्नरजवळील शिवनेरी हे छत्रपती शिवाजी महाराजांचे मान्य जन्मस्थान आहे. या एका घटनेपलीकडेही किल्ल्याचा दीर्घ प्रादेशिक इतिहास आहे.'],
   [['Entrances and water','दरवाजे आणि पाणी'],'Successive gateways and water provisions show how the hilltop settlement was defended and sustained. Their present condition reflects centuries of use and repair.','सलग दरवाजे आणि जलव्यवस्था डोंगरावरील वस्तीचे संरक्षण व दैनंदिन जीवन समजावतात. आजची अवस्था दीर्घ वापर आणि दुरुस्तीचे परिणाम दर्शवते.'],
   [['History and memory','इतिहास आणि स्मृती'],'Stories about the name and childhood of Chhatrapati Shivaji Maharaj are important cultural memories; precise dialogue or ceremony should not be presented as documented fact without a contemporary source.','छत्रपती शिवाजी महाराजांच्या नावाशी व बालपणाशी संबंधित कथा महत्त्वाच्या सांस्कृतिक स्मृती आहेत; समकालीन पुरावा नसताना नेमके संवाद किंवा विधी सिद्ध इतिहास म्हणून मांडू नयेत.']
  ]},
 'fort-sindhudurg':{
  title:['A sea fort at Malvan','मालवणचा जलदुर्ग'],place:['Malvan coast, Sindhudurg district · sea fort','मालवण किनारा, सिंधुदुर्ग जिल्हा · जलदुर्ग'],source:['gazetteer','sarkar'],sections:[
   [['Coastal defence','किनाऱ्याचे संरक्षण'],'Sindhudurg occupies an offshore site at Malvan. Its position illustrates the importance of maritime defence and coastal access to the seventeenth-century state.','मालवणसमोरील बेटावर सिंधुदुर्ग आहे. सतराव्या शतकातील राज्यासाठी सागरी संरक्षण आणि किनारी दळणवळणाचे महत्त्व त्यातून दिसते.'],
   [['Building in the sea','समुद्रातील बांधकाम'],'Walls, landing access and fresh-water provisions make the fort a useful study of coastal engineering. Exact quantities of construction materials need documentary support.','तटबंदी, प्रवेशमार्ग आणि गोड्या पाण्याची सोय यांमुळे किनारी स्थापत्याचा अभ्यास करता येतो. बांधकामातील साहित्याच्या नेमक्या प्रमाणासाठी दस्तऐवजी आधार आवश्यक आहे.'],
   [['The wider network','विस्तृत सागरी जाळे'],'The fort was one part of a wider coastal strategy, alongside ships, harbours and other strongholds. A single fort should not stand in for the entire naval history.','जहाजे, बंदरे आणि इतर किल्ल्यांसह हा गड व्यापक किनारी व्यवस्थेचा भाग होता. एका किल्ल्यावरून संपूर्ण आरमारी इतिहास सांगता येत नाही.']
  ]},
 'fort-sinhagad':{
  title:['Kondhana and its memory','कोंढाणा आणि त्याची स्मृती'],place:['Near Pune · hill fort','पुण्याजवळ · गिरिदुर्ग'],source:['sarkar','gazetteer'],sections:[
   [['The 1670 recapture','१६७० मधील पुनर्जय'],'Maratha forces under Tanaji Malusare recaptured Kondhana in 1670, and Tanaji died in the fighting. Later retellings made the episode a lasting account of sacrifice.','१६७० मध्ये तानाजी मालुसरे यांच्या नेतृत्वाखाली मराठा सैन्याने कोंढाणा परत घेतला; लढाईत तानाजी पडले. नंतरच्या कथनांनी या प्रसंगाला त्यागाचे स्मरणरूप दिले.'],
   [['Name and saying','नाव आणि प्रसिद्ध वाक्य'],'The saying “Gad aala, pan Sinha gela” is widely repeated in tradition. Its exact wording and the story of the fort’s renaming should not be treated as verified contemporary quotation.','“गड आला, पण सिंह गेला” हे वाक्य परंपरेत प्रसिद्ध आहे. त्याचे अचूक शब्द आणि नामांतराची कथा समकालीन प्रमाणित उद्धरण म्हणून मांडू नये.'],
   [['Why terrain mattered','भूभागाचे महत्त्व'],'Steep approaches and fortified entrances shaped the assault. Interpretive diagrams should show the terrain without claiming an exact route for every participant.','चढाईचे उतार आणि संरक्षित प्रवेशमार्ग यांनी हल्ल्यावर परिणाम केला. माहितीचित्रांनी भूभाग दाखवावा, पण प्रत्येकाची अचूक वाट निश्चित असल्याचा दावा करू नये.']
  ]},
 'fort-panhala':{
  title:['Panhala and the 1660 siege','पन्हाळा आणि १६६० चा वेढा'],place:['Near Kolhapur · hill fort','कोल्हापूरजवळ · गिरिदुर्ग'],source:['sarkar','gazetteer'],sections:[
   [['A regional stronghold','प्रादेशिक दुर्ग'],'Panhala guarded routes across the Kolhapur region. Its scale and surviving gateways, walls and water systems show its long strategic use.','पन्हाळा कोल्हापूर परिसरातील मार्गांवर नजर ठेवत होता. त्याचा विस्तार, दरवाजे, तटबंदी आणि जलरचना दीर्घ सामरिक वापर दाखवतात.'],
   [['Siege and departure','वेढा आणि सुटका'],'Siddi Jauhar’s forces besieged Chhatrapati Shivaji Maharaj at Panhala in 1660. He left for Vishalgad; the subsequent fighting at Pavan Khind became central to regional memory.','१६६० मध्ये सिद्दी जौहरच्या सैन्याने छत्रपती शिवाजी महाराजांना पन्हाळ्यावर वेढले. त्यांनी विशाळगडाकडे प्रयाण केले; पावनखिंडीतील पुढील लढा प्रादेशिक स्मृतीचा महत्त्वाचा भाग ठरला.'],
   [['Accounts and tradition','साधने आणि परंपरा'],'The accounts of Shiva Kashid and Baji Prabhu Deshpande are central to later narratives. Specific dialogue, disguise details and exact movements require source-by-source comparison.','शिवा काशीद आणि बाजीप्रभू देशपांडे यांचे प्रसंग नंतरच्या कथनांत महत्त्वाचे आहेत. नेमके संवाद, वेषांतर आणि हालचाली साधनांनुसार तपासाव्या लागतात.']
  ]}
};
function Citation({ids,lang}){return <details className="citation"><summary>{lang==='mr'?'पुरावे व संदर्भ':'Evidence & references'}</summary><ul>{ids.map(id=><li key={id}><strong>{sources[id].title}</strong> — {sources[id].author}. <span>{sources[id].kind}.</span> {sources[id].detail} {sources[id].url&&<a href={sources[id].url} target="_blank" rel="noreferrer">{lang==='mr'?'संस्था':'Institution'}</a>}</li>)}</ul></details>}
export function FortExhibition({slug,lang}){const entry=fortData[slug];if(!entry)return null;const index=lang==='mr'?1:0;return <section className="museum-exhibit" aria-labelledby="museum-exhibit-title"><div className="museum-exhibit__intro"><p className="museum-kicker">{lang==='mr'?'दुर्गदालन · अधिक जाणून घ्या':'FORT EXHIBITION · FURTHER READING'}</p><h2 id="museum-exhibit-title">{entry.title[index]}</h2><p>{entry.place[index]}</p></div><div className="museum-exhibit__grid">{entry.sections.map(([heading,en,mr],i)=><article key={i} className="museum-exhibit__panel"><span className="museum-exhibit__number">0{i+1}</span><h3>{heading[index]}</h3><p>{index?mr:en}</p></article>)}</div><Citation ids={entry.source} lang={lang}/></section>}
export function CampaignExhibition({lang}){const index=lang==='mr'?1:0;const entries=[
 [['Diplomacy before expansion','विस्तारापूर्वीचे राजकारण'],'Relations with the Qutb Shahi court at Golconda formed part of the political setting of the southern campaign. The precise terms need comparison across chronicles and records.','गोवळकोंड्याच्या कुतुबशाही दरबाराशी संबंध दक्षिण मोहिमेच्या राजकीय पार्श्वभूमीचा भाग होते. नेमक्या अटींसाठी विविध साधनांची तुलना आवश्यक आहे.'],
 [['The Carnatic strongholds','कर्नाटकातील दुर्ग'],'Jinji and Vellore are central to accounts of the campaign. Avoid treating the expedition as a single uninterrupted march or assigning an exact route without contemporary evidence.','जिंजी आणि वेल्लोर हे मोहिमेच्या कथनातील महत्त्वाचे दुर्ग आहेत. समकालीन पुराव्याशिवाय मोहिमेला एक अखंड वाटचाल किंवा अचूक मार्ग देऊ नये.'],
 [['A longer southern presence','दक्षिणेतील दीर्घ उपस्थिती'],'The southern foothold outlasted the original expedition. Its later importance belongs to a different phase of Maratha history and should be read separately from the events of 1677–78.','दक्षिणेतील आधारक्षेत्र मूळ मोहिमेनंतरही टिकले. पुढील महत्त्व हा मराठा इतिहासातील वेगळा टप्पा आहे; तो १६७७–७८ च्या घटनांपासून वेगळा अभ्यासावा.']
 ];return <section className="museum-exhibit" aria-labelledby="campaign-exhibit-title"><div className="museum-exhibit__intro"><p className="museum-kicker">{index?'मोहिमेचा संदर्भ':'CAMPAIGN CONTEXT'}</p><h2 id="campaign-exhibit-title">{index?'दक्षिण मोहिमेचा विस्तृत संदर्भ':'Reading the Southern Campaign'}</h2></div><div className="museum-exhibit__grid">{entries.map(([title,en,mr],i)=><article key={i} className="museum-exhibit__panel"><span className="museum-exhibit__number">0{i+1}</span><h3>{title[index]}</h3><p>{index?mr:en}</p></article>)}</div><Citation ids={['sarkar','sabhasad']} lang={lang}/></section>}
export function SourceContext({slug,lang}){const mr=lang==='mr';return <aside className="source-context" aria-label={mr?'ऐतिहासिक पुरावे':'Historical evidence'}><p className="museum-kicker">{mr?'पुरावा नोंद':'EVIDENCE NOTE'}</p><h2>{slug==='letters'?(mr?'उद्धरणे कशी वाचावीत':'Reading attributed quotations'):(mr?'कालपट कसा वाचावा':'Reading the chronology')}</h2><p>{slug==='letters'?(mr?'येथील काही वाक्ये लोकप्रिय रूपात दिली आहेत. मूळ हस्तलिखित, दिनांक, पाठभेद आणि अचूक शब्द येथे प्रमाणित केलेले नाहीत; म्हणून त्यांना सत्यापित शब्दशः उद्धरण समजू नये. आज्ञापत्र हा नंतरचा ग्रंथ आहे.':'Some sayings on this page are given in popular form. Their manuscripts, dates, textual variants and exact wording have not been authenticated here; do not treat them as verified verbatim quotations. The Adnyapatra is a later work.'):(mr?'रायरेश्वर शपथेचे नाट्यमय तपशील परंपरेत येतात; समकालीन पुरावा निश्चित नाही. घटनांच्या तारखा आणि अर्थासाठी एकापेक्षा अधिक साधने तपासावीत.':'The dramatic details of the Raireshwar oath belong to later tradition; contemporary confirmation is uncertain. Dates and interpretations should be checked across more than one source.')}</p><Citation ids={slug==='letters'?['sabhasad','sarkar']:['sarkar','sabhasad']} lang={lang}/></aside>}
